"""
run_sql_analysis.py
-------------------
Executes every query in sql/analysis_queries.sql and writes each result
to outputs/sql/<name>.csv, plus a readable summary to outputs/sql_results.md.

Run:  python src/run_sql_analysis.py   (run build_database.py first)
"""

from pathlib import Path
import re
import sqlite3
import pandas as pd

ROOT = Path(__file__).resolve().parents[1]
DB = ROOT / "data" / "processed" / "superstore.db"
QUERIES = ROOT / "sql" / "analysis_queries.sql"
OUT_DIR = ROOT / "outputs" / "sql"
SUMMARY = ROOT / "outputs" / "sql_results.md"


def parse_queries(sql_text: str) -> list[tuple[str, str]]:
    """Split the file on '-- @name:' markers into (name, sql) pairs."""
    blocks = re.split(r"--\s*@name:\s*(\w+)", sql_text)[1:]   # [name, body, name, body...]
    return [(blocks[i], blocks[i + 1].strip()) for i in range(0, len(blocks), 2)]


def main() -> None:
    OUT_DIR.mkdir(parents=True, exist_ok=True)
    con = sqlite3.connect(DB)
    md = ["# SQL Analysis Results", "",
          "Generated by `src/run_sql_analysis.py` from `sql/analysis_queries.sql`.", ""]

    for name, sql in parse_queries(QUERIES.read_text()):
        df = pd.read_sql_query(sql, con)
        df.to_csv(OUT_DIR / f"{name}.csv", index=False)

        title = name.split("_", 1)[1].replace("_", " ").title()
        md += [f"## {name.split('_')[0]}. {title}", "",
               df.head(10).to_markdown(index=False), ""]
        if len(df) > 10:
            md += [f"_Showing 10 of {len(df)} rows._", ""]
        print(f"  {name:<32} {len(df):>4} rows")

    con.close()
    SUMMARY.write_text("\n".join(md))
    print(f"\nSaved -> outputs/sql/ and {SUMMARY.relative_to(ROOT)}")


if __name__ == "__main__":
    main()
